spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://localhost:5432/QLBanHang
    username: hungjava
    password: 123456
  jpa:
     properties:
       hibernate:
         dialect: org.hibernate.dialect.PostgreSQLDialect
     show-sql: true
     hibernate:
       ddl-auto: update
  sendgrid:
    api-key: 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
    from-email: soclash968@gmail.com
    templateId: d-40de060252c84dc59767a7590b210d61
    verificationLink: http://localhost:8080/user/confirm-email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  packages-to-scan: vn.hungjava.controller
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0